#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes
H=0
M=0
while [ $H -le 12 ] 
do
	echo "Hour: $H"
	M=0
	while [ $M -le 59 ] 
	do
		echo "$M"
		((M++))
	done
	((H++))
	done
