#!/usr/bin/env bash
#Programs that are detached from the terminal and running in the background are called daemons or processes

pid=/var/run/my_process.pid
aaa=manage_my_process

case $1 in
	
	start)
	        ./$aaa &
	        echo $! > $pid
	        echo "manage_my_process started"
	        ;;
						        
        stop)
		kill "$(cat $pid)"
		rm -f $pid
		echo "manage_my_process stopped"
		;;
						        
        restart)
		kill "$(less $pid)"
		rm -f $pid
		./$aaa &
		echo $! > $pid
		echo "manage_my_process restarted"
		;;
								
        *)
		 echo "Usage: manage_my_process {start|stop|restart}"
		;;
		esac
